export default {
  // For context API store data...
  album: null,
  albums: [],
  albumsLoading: false,
  albumValues: null,
  attemptingLogin: false,
  genre: "",
  genres: [],
  genresValue: [],
  greaterThanAlbumLengthInMinutes: "",
  greaterThanAlbumTotalTracks: "",
  greaterThanAlbumYear: "",
  greaterThanListenDate: "",
  greaterThanLongestTrackInSeconds: "",
  greaterThanShortestTrackInSeconds: "",
  isAuthenticated: null,
  lessThanAlbumLengthInMinutes: "",
  lessThanAlbumTotalTracks: "",
  lessThanAlbumYear: "",
  lessThanListenDate: "",
  lessThanLongestTrackInSeconds: "",
  lessThanShortestTrackInSeconds: "",
  light: "true",
  limit: 25,
  local_access_token: "",
  loginStep: 0,
  page: 1,
  password: "",
  primarySort: "orderNumber",
  primarySortOrder: "desc",
  search: "",
  secondarySort: "",
  secondarySortOrder: "asc",
  selectedAlbum: "",
  sidebarComponent: "Sidebar",
  sidebarClosed: true,
  sort: "-orderNumber",
  spotify_access_token: "",
  spotifyURI: "",
  startDate: new Date("06/01/18"),
  stats: {},
  username: "",
}